### ISSUE TITLE
ZIP wrong URL and warning for users

### ISSUE THREAD

**Issue by Trollwut** [dracula/nova_launcher#1]
Hey mate!

I appreciate your effort, and it looks awesome! :)

There are problems though:

- The ZIP in install.md is not linking to the right one. The linked one doesn't have the dracula folder in it.
- Restoring this theme deletes the current workspace!! This should definitely be a warning for the user (fortunately I made a backup before)

Is it somehow possible to just export/import the coloring, not the whole launcher layout?

**Comment by scientiac** [comment]
I had edited the template of Dracula, hence the link I created was supposed to be the link after Dracula published it. 

I have edited the link to match my own repo now. 

And yeah I made the layout with rounded corners and all to make it pretty, just the "colors" version with the original nova layout will be uploaded within an hour. (Thanks for the advice.)

**Comment by Trollwut** [comment]
Totally understand. :)

We should just warn the user that restoring this theme might delete their own layout (which they should backup first).

**Comment by scientiac** [comment]
i uploaded the layout,check it out

and thanks again

**Comment by Trollwut** [comment]
Thanks, works!

But it will still replace the user's layout. I guess this is a given thing and you can't simply just import the colors?

**Comment by scientiac** [comment]
Yeah unfortunately, that's how nova works.  Its a backup file,. The users should be warned and they are, and the ones familiar to nova will immediately recognize that it does that anyways.

I might be able to write step by step instructions to change the colors but it will be complicated and confusing  and difficult than just applying the backup file.

What do you think ? Should I write that?

**Comment by scientiac** [comment]
I did write a step by step guide and put it on the INSTALL.md file as well as in a file in Dracula Directory. 

Can you check it out.
