### ISSUE TITLE
Icon library used in the screenshot and the search bar colour looks bright

### ISSUE THREAD

**Issue by sanjayen** [dracula/nova_launcher#5]
Thank you for the step-by-step Nova Launcher configuration. However, what icon library did you use in the screenshot as that gels well with the Dracula theme. And the pink that I can see for the Search Drawer is too bright when compared to the one in your screenshot. Did you use a subtle value?

**Comment by scientiac** [comment]
It's the charcoal icon pack , it's linked in the installation instructions on Dracula's website.

It's very simple to change colors of the bar, you might want to dial the darkness by your likings.

**Comment by sanjayen** [comment]
Missed seeing that, closing this issue.
